### ISSUE TITLE
Hints on extension for a multi-chat room app

### ISSUE THREAD

**Issue by CesMak** [miguelgrinberg/microflack_messages#9]
Hey Miguel,
I do hope to not bore you (with all my questions), but I would be pleased if you have some hints for me on how to get started extending the microflack_app for a multi-chat room app. 

**The Design**
I therefore extended each user with an additional roomid field. The idea is that everyone can login to a chat room with a roomid and can only see the messages inside the room. Additionally it should be possible to send from the server side messages to all users (broadcasting) inside a room and also to only specific clients. 

The original message workflow is like this:
app.socket.emit('post_message', {source: args.message}, app.token.get('token'));
→ [socketio]      : on_post_message(data, token) 
→ [socketio]       rv = requests.post('/api/messages', json=data, headers={'Authorization': 'Bearer ' + token},  
→ [messages]    @app.route('/api/messages', methods=['POST']) – def new_message():
→ [ui] if a new message is registered in the db it is rendered to the ui 

Now what I wanted to do is to include 
join_room, leave_room inside socketio. But currently socketio works with sending requests so I cannot use  e.g.
`emit('status', {'msg': session.get('name') + ' has entered the room.'}, room=room)`
inside socketio. For this reason I wondered where I have to use the emit? 
Do I have to handle diffrent rooms all on client side and should each message contain instead the roomid it is send to?

**Comment by miguelgrinberg** [comment]
The join_room call for each user would happen when the user logs in. So you'll need to add a new event handler in the socketio server to take the room and put the user in it.

Once the user is in the room it'll start receiving events from that room. Then in the post message event you can add the room argument in the POST to /messages, so that the messages service can then emit the model update only to the correct room.

Also, I have a multi-room chat example here: https://github.com/miguelgrinberg/Flask-SocketIO-Chat that might be useful for you to review. This one is monolitic, not based on microservices.

**Comment by CesMak** [comment]
Hey thanks for these super tipps - it works :+1:  

However,

I still wonder how to send messages from the server let's say I would like to send a message into the room after a user login:

    requests.post('/api/messages', json=data, headers={'Authorization': 'Bearer ' + token}, raise_for_status=False)

But this requires a token - and somehow I do not get it how to get / generate a token from the server side....

Code Example from users service
```python
@app.route('/api/users', methods=['POST'])
def new_user():
    """
    Register a new user.
    This endpoint is publicly available.
    """
    user = User.create(request.get_json() or {})
    if User.query.filter_by(nickname=user.nickname).first() is not None:
        abort(400)
    db.session.add(user)
    db.session.commit()
    r = jsonify(user.to_dict())
    r.status_code = 201
    r.headers['Location'] = url_for('get_user', id=user.id)

    data = {}
    data["roomid"] = 0
    data["source"] = "huhuuu"
    # final_str = request.get_json()["nickname"]+":"+request.get_json()["password"]
    # print(base64.b64encode(final_str.encode('utf-8')).decode('utf-8'))
    # token = requests.post('/api/tokens', headers={'Authorization': 'Basic ' + base64.b64encode(final_str.encode('utf-8')).decode('utf-8')}, raise_for_status=False)
    requests.post('/api/messages', json=data, headers={'Authorization': 'Bearer ' + token}, raise_for_status=False)
    return r
```

**Comment by miguelgrinberg** [comment]
The server does not need to go through the HTTP interface to post a message. You can instantiate a `socketio` object and emit through it directly, in the same way the messages service does it.

**Comment by CesMak** [comment]
Yes I thougt about doing it directly but then I do not have the automatic rendering processes from the messages. 

Another problem that I have is: I would like to send server messages just to one user (using e.g. emit(..., room=request.sid) however the **sid** only exists inside the socketio handler which is not available in a http handler e.g. inside *new_user():*

**Comment by miguelgrinberg** [comment]
Okay. Don't be afraid to change the design to fit your needs. Here are a few options that you can consider:

- allocate a token to be used internally, then you can send an authenticated POST request to messages from any of the services
- allow requests between services to work without authentication
- move the message rendering functionality to the common library so that it can be used from multiple places

You can also store the `sid` in the user database if you need it outside of the socketio service.
